source 'https://rubygems.org'


gem 'rails', '4.2.0'

gem 'rails-api'

gem 'spring', :group => :development


gem 'sqlite3'

gem 'pg'

gem 'dotenv-rails'

gem 'httparty'

gem 'awesome_print'

gem 'typhoeus'

gem 'nokogiri'

gem 'mandrill-api'

group :development, :test do
  # gem 'debugger'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'
end

group :test do
  gem 'faker', '~>1.1.2'
  gem 'capybara'
  gem 'database_cleaner', '~>1.0.1'
  gem 'launchy', '~>2.3.0'
  gem 'selenium-webdriver', '~>2.39.0'
  gem 'simplecov'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
